#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IO-Interface
Version  : 1.09
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/L/LD/LDS/IO-Interface-1.09.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/L/LD/LDS/IO-Interface-1.09.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libio-interface-perl/libio-interface-perl_1.09-1.debian.tar.xz
Summary  : 'Access and modify network interface card configuration'
Group    : Development/Tools
License  : Artistic-1.0-Perl Artistic-2.0
Requires: perl-IO-Interface-lib
Requires: perl-IO-Interface-license
Requires: perl-IO-Interface-man
Requires: perl(Module::Build)
BuildRequires : perl(Module::Build)

%description
LibIO-Interface-Perl
====================
Perl interface to Unix network interface API

%package lib
Summary: lib components for the perl-IO-Interface package.
Group: Libraries
Requires: perl-IO-Interface-license

%description lib
lib components for the perl-IO-Interface package.


%package license
Summary: license components for the perl-IO-Interface package.
Group: Default

%description license
license components for the perl-IO-Interface package.


%package man
Summary: man components for the perl-IO-Interface package.
Group: Default

%description man
man components for the perl-IO-Interface package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n IO-Interface-1.09
mkdir -p %{_topdir}/BUILD/IO-Interface-1.09/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/IO-Interface-1.09/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-IO-Interface
cp LICENSE %{buildroot}/usr/share/doc/perl-IO-Interface/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-IO-Interface/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/IO/Interface.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/IO/Interface/Simple.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/IO/Interface/Interface.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-IO-Interface/LICENSE
/usr/share/doc/perl-IO-Interface/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/IO::Interface.3
/usr/share/man/man3/IO::Interface::Simple.3
